version: "3.3"
services:
  pushkind-approve:
    build: .
    hostname: pushkind-approve
    networks:
      - pushkind-network
    container_name: pushkind-approve
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - FLASK_APP
      - SECRET_KEY
      - APPLICATION_TITLE
      - ADMIN_EMAIL
      - MAIL_SERVER
      - MAIL_PORT
      - MAIL_USE_SSL
      - MAIL_USERNAME
      - MAIL_SENDERNAME
      - MAIL_PASSWORD
      - MOMENT_DEFAULT_FORMAT
      - DATABASE_URL
    links:
      - pushkind-mysql
    volumes:
      - ./data/static:/home/pushkind/app/static/upload
    restart: unless-stopped
  pushkind-mysql:
    image: "mysql:latest"
    hostname: pushkind-mysql
    networks:
      - pushkind-network
    container_name: pushkind-mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./data/db:/var/lib/mysql
    restart: unless-stopped

networks:
  pushkind-network: {}